In [91]:
import pandas as pd
import numpy as np

In [92]:
mydict = {
    "car":['BMw',"Audi"],
    "numbers":[1,2]
}

df = pd.DataFrame(mydict)
df

car  numbers
0   BMw        1
1  Audi        2

Series

In [93]:
mys = [1,2,3,4]
ind = ['a','b','c','d']
s = pd.Series(mys,index=ind)
print(s['d'])

4


Create series as key value dict

In [94]:
myd = {"a":"apple","b":"Banana"}
d = pd.Series(myd)
d

a     apple
b    Banana
dtype: object

Suppose you wanna put some key values in series not all:

In [95]:
myd = {"a":1,"b":2,"c":3,'d':4}
d = pd.Series(myd,index=['a','b'])
d

a    1
b    2
dtype: int64

Locate row in dataframe

In [96]:
df

car  numbers
0   BMw        1
1  Audi        2

In [97]:
print(df["car"]) # here when directly you wanna access something go by the column that just requires column name

0     BMw
1    Audi
Name: car, dtype: object


In [98]:
print(df.loc[1]) # when need to access row use loc and row number

car        Audi
numbers       2
Name: 1, dtype: object


In [99]:

data = {
  "calories": [420, 380, 390],
  "duration": [50, 40, 45]
}

dc = data['calories']
createindex=[]
for i in range(len(dc)):
  createindex.append(f"day{i+1}")
  print(createindex)

mydataframe = pd.DataFrame(data,index=createindex)
mydataframe

['day1']
['day1', 'day2']
['day1', 'day2', 'day3']


calories  duration
day1       420        50
day2       380        40
day3       390        45

In [100]:
print(mydataframe.info())

<class 'pandas.core.frame.DataFrame'>
Index: 3 entries, day1 to day3
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   calories  3 non-null      int64
 1   duration  3 non-null      int64
dtypes: int64(2)
memory usage: 180.0+ bytes
None


# **Numpy Start**

In [101]:
arr = np.array([1,2,3,4])
print(type(arr))

<class 'numpy.ndarray'>


In [102]:
arr2 = np.array([[1,2,3],[4,5,6]])
print(arr2.ndim) # number of dimensions

2


In [103]:
arr3 = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
arr3

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [104]:
arr4 = np.array([1,2,3,4],ndmin=5) # we can set dimensions also
print(arr4.ndim)

5


In [105]:
arr3[1,1,2]

np.int64(6)

Slicing

In [106]:
arrs = np.array(['a','b','c','d','f','g','h','i'])
print(arrs[0::2])

['a' 'c' 'f' 'h']


Datatype

In [107]:
arr = np.array([1,2,3,4,5,6,7,8])
print(arr.dtype)

int64


In [108]:
arrf = np.array([1.1,1.2,1.3])
print(arrf.dtype)

float64


In [109]:
print(arrs.dtype)

<U1


convert dtype to another dtype

In [110]:
arrw = np.array([1,2,3,4,5,6],dtype='S')
print(arrw)

[b'1' b'2' b'3' b'4' b'5' b'6']


In [111]:
print(arr3.shape)

(2, 2, 3)


In [112]:
print(arr3)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


convert dimensions of array by using reshape

In [118]:
arrf = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
cg = arrf.reshape(2,2,3)
print(cg)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


concatenate

In [122]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
arr3 = np.concatenate((arr1,arr2))
print(arr3)

[1 2 3 4 5 6]


In [126]:
arrl = np.array([[1,2,3,4]])
arrp = np.array([[8,9,0,11]])
arrt = np.concatenate((arrl,arrp))
print(arrt)

[[ 1  2  3  4]
 [ 8  9  0 11]]


Split

In [129]:
print(np.array_split(arr1,2))

[array([1, 2]), array([3])]


In [136]:
arrq= np.array([1,2,3,4,5,6,7,4,4,1])
x = np.where(arrq==4)
x

(array([3, 7, 8]),)

SearchSorted

In [137]:
arrw = np.array([1,2,3,4,5,6,7])
x = np.searchsorted(arrw,3)
x

np.int64(2)