In [2]:
import numpy as np

Array_______

In [19]:
arr = np.array([1,2,3,4,5])
print(arr.dtype)
print(type(arr))

int64
<class 'numpy.ndarray'>


In [23]:
arr_float = np.array([1,2.4,5.6,2,9.0])
print(arr_float.dtype)
print(type(arr_float))

float64
<class 'numpy.ndarray'>


In [24]:
arr_multiple = np.array([1,"2",3,4.6])
print(arr_multiple.dtype) # basically its unicode 32
print(type(arr_multiple))

<U32
<class 'numpy.ndarray'>


In [31]:
arr_negetive = np.array([-1,2,-0])
print(arr_negetive)

[-1  2  0]


In [46]:
np_single = np.array(35)
print(np_single.ndim)

0


In [43]:
arr_twoD = np.array([[1,2,3],[-3,6,7]])
print(arr_twoD)
print(type(arr_twoD))

[[ 1  2  3]
 [-3  6  7]]
<class 'numpy.ndarray'>


In [47]:
arr_threeD = np.array([[[1,2,3],[4,5,6]],
                       [[7,8,9],[10,11,12]]])
print(arr_threeD)
print(arr_threeD.ndim)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
3


In [ ]:
arr_fourd = np.array([[]])