In [3]:
import numpy as np

Array_______

In [4]:
arr = np.array([1,2,3,4,5])
print(arr.dtype)
print(type(arr))

int64
<class 'numpy.ndarray'>


In [5]:
arr_float = np.array([1,2.4,5.6,2,9.0])
print(arr_float.dtype)
print(type(arr_float))

float64
<class 'numpy.ndarray'>


In [6]:
arr_multiple = np.array([1,"2",3,4.6])
print(arr_multiple.dtype) # basically its unicode 32
print(type(arr_multiple))

<U32
<class 'numpy.ndarray'>


In [7]:
arr_negetive = np.array([-1,2,-0])
print(arr_negetive)

[-1  2  0]


In [8]:
np_single = np.array(35)
print(np_single.ndim)

0


In [9]:
arr_twoD = np.array([[1,2,3],[-3,6,7]])
print(arr_twoD)
print(type(arr_twoD))

[[ 1  2  3]
 [-3  6  7]]
<class 'numpy.ndarray'>


In [10]:
arr_threeD = np.array([[[1,2,3],[4,5,6]],
                       [[7,8,9],[10,11,12]]])
print(arr_threeD)
print(arr_threeD.ndim)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
3


In [11]:
arr_fourD = np.array([[[[1,2,3],[1,2,3]],
                      [[4,5,6],[4,5,6]],
                      [[7,8,9],[7,8,9]]],
                      [[[1,2,3],[1,2,3]],
                      [[4,5,6],[4,5,6]],
                      [[7,8,9],[7,8,9]]]])
print(arr_fourD.ndim)

4


In [12]:
# Higher dimensions
higher_arr = np.array([1,2,3,4,5],ndmin=15)
print(higher_arr)
print(higher_arr.ndim)

[[[[[[[[[[[[[[[1 2 3 4 5]]]]]]]]]]]]]]]
15


Indexing______

In [13]:
indArr = np.array([1,2,3,4,5,6])
print(indArr[-2])

5


In [14]:
print(indArr[5] + indArr[-1])

12


In [15]:
#Access the element on the first row, second column:
print(arr_twoD)
print(arr_twoD[0,1])
print(arr_twoD[1,0])

[[ 1  2  3]
 [-3  6  7]]
2
-3


In [16]:
# Access the third element of the second array of the first array:
print(arr_threeD)
print(arr_threeD[1,1,2])

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
12


Slicing_____  

In [17]:
#[start:end:step] here is the rule to remember: the end point always gives value of a previous index (5 means 4th index)
print(indArr)
print(indArr[0:1])

[1 2 3 4 5 6]
[1]


In [18]:
#Slice elements from index 4 to the end of the array:
print(indArr[4:])

[5 6]


In [19]:
# Negetive slicing:
print(indArr[-3:-1])

[4 5]


In [20]:
#Return every other element from index 1 to index 5 using STEP:
print(indArr)
print(indArr[1:5:1]) # now here the steps never start counting with 0 so when you set 1 it basicallly counts the same number no nothing to remove
print(indArr[1:5:2])

[1 2 3 4 5 6]
[2 3 4 5]
[2 4]


In [21]:
# Return every other element from the entire array:
print(indArr[::2])

[1 3 5]


In [22]:
# Slicing 2D Array:
Two_arr = np.array([
    [1,2,3,4,5,6,20],
    [7,8,9,10,11,12,30]])
print(Two_arr)

#From the second element, slice elements from index 1 to index 4 (not included):
print("slicing:")
print(Two_arr[1,1:-1:2])


[[ 1  2  3  4  5  6 20]
 [ 7  8  9 10 11 12 30]]
slicing:
[ 8 10 12]


In [23]:
# From both elements, return index 2:
print(Two_arr[::,2])

[3 9]


Data Types_____

In [24]:
arr_u = np.array(['a','s','d','f'])
print(arr_u)
print(arr_u.dtype)

['a' 's' 'd' 'f']
<U1


In [25]:
arr_s = np.array(["m","s","d","f"])
print(arr_s)
print(arr_s.dtype)

['m' 's' 'd' 'f']
<U1


In [26]:
arr_s[0] = "Mihir"
print(arr_s)

['M' 's' 'd' 'f']


In [27]:
setDtype_arr = np.array([1,2,3,4,5], dtype='S')
print(setDtype_arr)
print(setDtype_arr.dtype)

[b'1' b'2' b'3' b'4' b'5']
|S1


In [28]:
arr = np.array(["hello", "worlds"], dtype='S')
print(arr)
print(arr.dtype)

[b'hello' b'worlds']
|S6


In [29]:
arr_i = np.array([1,2,3,4,5], dtype='i4')
print(arr_i)
print(arr_i.dtype)

[1 2 3 4 5]
int32


In [30]:
# arr_error = np.array(['a','2'],dtype = 'i')
# print(arr_error)

In [31]:
arr_co = np.array([1.1,2.2,0.0])
print(arr_co)
arr_c = arr_co.astype(bool)
print(arr_c)

[1.1 2.2 0. ]
[ True  True False]


Copy() VS View()

In [32]:
arr_Original = np.array([1,2,3,4])
arr_copy = arr_Original.copy()
arr_Original[0] = 5
print(arr_Original)
print(arr_copy)

[5 2 3 4]
[1 2 3 4]


In [33]:
arr_view = arr_Original.view()
arr_Original[0] = 0
print(arr_Original)
print(arr_view)

[0 2 3 4]
[0 2 3 4]


In [34]:
arr_v = arr_Original
arr_Original[0] = -1
print(arr_Original)
print(arr_v)

[-1  2  3  4]
[-1  2  3  4]


In [35]:

arr = np.array([1, 2, 3, 4, 5])

x = arr.copy()
y = arr.view()

print(x.base)
print(y.base)

None
[1 2 3 4 5]


Shape_____

In [36]:
print(arr_twoD.shape)
print(arr_twoD)

(2, 3)
[[ 1  2  3]
 [-3  6  7]]


In [37]:
print(arr_threeD.shape)
print(arr_threeD)

(2, 2, 3)
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [38]:
another_arr_threeD = np.array([
                              [[1,2,3],[1,2,3],[1,2,3]],
                              [[4,5,6],[4,5,6],[4,5,6]],
                              [[7,8,9],[7,8,9],[7,8,9]]
                              ])
print(another_arr_threeD.shape)

(3, 3, 3)


In [39]:
anotherr_arr_threeD = np.array([
                              [[1,2,3],[1,2,3]],
                              [[7,8,9],[7,8,9]]
                              ],ndmin = 64)
print(anotherr_arr_threeD.ndim)

64


Reshaping______

In [40]:
new_arr = np.array([1,2,3,4,5,6,7,8])
newArr = new_arr.reshape(4,2)
print(newArr)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [41]:
new_arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr = new_arr.reshape(3,2,-2)
print(newarr)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


Iterating Arrays_____

In [42]:
print(newarr.ndim)
for i in newarr:
 # print("i::",i)
  for j in i:
   # print("J::",j)
    for k in j:
      print("K::",k)

3
K:: 1
K:: 2
K:: 3
K:: 4
K:: 5
K:: 6
K:: 7
K:: 8
K:: 9
K:: 10
K:: 11
K:: 12


In [43]:
for i in np.nditer(new_arr):
  print(i)

1
2
3
4
5
6
7
8
9
10
11
12


In [44]:
for i in np.nditer(new_arr,flags=['buffered'],op_dtypes=['S']):
  print(i)

np.bytes_(b'1')
np.bytes_(b'2')
np.bytes_(b'3')
np.bytes_(b'4')
np.bytes_(b'5')
np.bytes_(b'6')
np.bytes_(b'7')
np.bytes_(b'8')
np.bytes_(b'9')
np.bytes_(b'10')
np.bytes_(b'11')
np.bytes_(b'12')


Concatenate

In [45]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([6,7,8,9])
arr4 = np.array([11,1,2])
arr3 = np.concatenate((arr2,arr1,arr4))
print(arr3)

[ 6  7  8  9  1  2  3  4  5 11  1  2]


In [50]:
#Two D array concatenate
arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([[7,8,9],[10,11,12]])
arr3 = np.concatenate((arr1,arr2),axis=0)
print(arr3)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [55]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.hstack((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


In [56]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.vstack((arr1, arr2))

print(arr)

[[1 2 3]
 [4 5 6]]


In [57]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.dstack((arr1, arr2))

print(arr)

[[[1 4]
  [2 5]
  [3 6]]]


Splitting Array

In [65]:
arr1 = np.array([1,2,3,4,5,6,7,8,9])
arr2 = np.array([4,5,6])
arr3 = np.array_split(arr1,2)
print(arr3)

[array([1, 2, 3, 4, 5]), array([6, 7, 8, 9])]


In [71]:
arr1 = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
arr3c = np.array_split(arr1,3,axis=1)
print(arr3c)

[array([[ 1],
       [ 4],
       [ 7],
       [10]]), array([[ 2],
       [ 5],
       [ 8],
       [11]]), array([[ 3],
       [ 6],
       [ 9],
       [12]])]


Search Array

In [76]:
arr1 = np.array([1,2,3,4,4,5,6,7,8,8])
x = np.where(arr1==4)
print(x)

(array([3, 4]),)


In [78]:
arr1 = np.array([1,2,3,4,5,6,7,8,9])
x = np.where(arr1%2==0)
print(x)

(array([1, 3, 5, 7]),)


In [85]:
arr1 = np.array([2,1])
x = np.searchsorted(arr1,2)
print(x)

2


In [86]:
arr = np.array([1, 3, 5, 7])

x = np.searchsorted(arr, [2, 4, 6])

print(x)

[1 2 3]


Sorting

In [88]:
arr = np.array([True, False, True])

print(np.sort(arr))

[False  True  True]


In [89]:
arr = np.array([[3, 2, 4], [5, 0, 1]])

print(np.sort(arr))

[[2 3 4]
 [0 1 5]]


Filter

In [91]:
arr = np.array([41, 42, 43, 44])

x = [True, False, True, False]

newarr = arr[x]

print(newarr)

[41 43]


In [93]:
arr = np.array([41, 42, 43, 44])

filter_arr = arr > 42

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False False  True  True]
[43 44]


In [94]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

filter_arr = arr % 2 == 0

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False  True False  True False  True False]
[2 4 6]
